# Generated by Django 4.2.30 on 2026-06-11 09:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dossiers', '0007_remove_registrecivil_nom_complet_personne_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilAgent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut_actuel', models.CharField(choices=[('en_ligne', 'En Ligne (Disponible)'), ('en_pause', 'En Pause'), ('hors_ligne', 'Hors Ligne'), ('surcharge', 'Surchargé (Ne pas déranger)')], db_index=True, default='hors_ligne', max_length=20, verbose_name='Statut Actuel')),
                ('capacite_maximale', models.PositiveIntegerField(default=15, help_text='Le nombre de dossiers que cet agent peut gérer en parallèle.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Capacité max de dossiers simultanés')),
                ('competences_types_dossiers', models.JSONField(blank=True, default=list, help_text="Liste des types de dossiers que cet agent est habilité à traiter (ex: ['birth_certificate', 'marriage_certificate']).", verbose_name='Compétences (Types de dossiers supportés)')),
                ('score_performance_global', models.FloatField(default=100.0, help_text='Calculé automatiquement par le moteur de scoring (Qualité + Rapidité).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Score de Performance Global')),
                ('temps_moyen_traitement_minutes', models.PositiveIntegerField(default=30, help_text="Sert à évaluer la charge cognitive prévisionnelle de l'agent.", verbose_name='Temps moyen de traitement (minutes)')),
                ('dossiers_traites_historique', models.PositiveIntegerField(default=0, verbose_name='Total Historique de Dossiers Traités')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_attribution', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur Agent')),
            ],
            options={
                'verbose_name': "Profil d'Attribution Agent",
                'verbose_name_plural': "Profils d'Attribution Agents",
                'ordering': ['-score_performance_global', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='JournalAttribution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('attribution_initiale', 'Attribution Initiale'), ('changement_statut', 'Changement de Statut'), ('reattribution_manuelle', 'Réattribution Manuelle'), ('reattribution_automatique', 'Réattribution Automatique (Moteur)'), ('escalade_sla', 'Escalade de SLA'), ('timeout_agent', "Délai d'inactivité dépassé")], db_index=True, max_length=50, verbose_name='Action effectuée')),
                ('motif_detaille', models.TextField(help_text="Explication technique ou métier justifiant l'action.", verbose_name="Motif Détaillé de l'Action")),
                ('anciennes_valeurs', models.JSONField(blank=True, default=dict, help_text='Snapshot des données avant la modification (pour la traçabilité complète).', verbose_name='Anciennes Valeurs')),
                ('agent_concerne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_actions', to='etat_civil.profilagent', verbose_name='Agent Concerné')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_attributions', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': "Journal d'Attribution",
                'verbose_name_plural': "Journaux d'Attribution",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttributionDossier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('attribue', 'Attribué (Non ouvert)'), ('en_cours', 'En Cours de Traitement'), ('termine', 'Traitement Terminé'), ('escalade', 'Escaladé (SLA Dépassé)'), ('reattribue', 'Réattribué à un autre agent')], db_index=True, default='attribue', max_length=20, verbose_name="Statut de l'Attribution")),
                ('niveau_priorite', models.IntegerField(choices=[(1, 'Basse'), (2, 'Normale'), (3, 'Haute'), (4, 'Urgente (Alerte)'), (5, 'Critique (Escalade Supérieure)')], db_index=True, default=2, verbose_name='Niveau de Priorité')),
                ('date_limite_sla', models.DateTimeField(help_text='Date à laquelle le dossier doit impérativement être traité avant escalade.', verbose_name='Date Limite SLA')),
                ('date_traitement_effectif', models.DateTimeField(blank=True, null=True, verbose_name='Date de Traitement Effectif')),
                ('score_matching_initial', models.FloatField(default=0.0, help_text="Le score généré par l'algorithme justifiant cette attribution.", verbose_name='Score de Matching Initial')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='etat_civil.profilagent', verbose_name='Agent Assigné')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions_historique', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Attribution de Dossier',
                'verbose_name_plural': 'Attributions de Dossiers',
                'ordering': ['-niveau_priorite', 'date_limite_sla'],
            },
        ),
        migrations.AddIndex(
            model_name='profilagent',
            index=models.Index(fields=['statut_actuel', 'score_performance_global'], name='etat_civil__statut__8e0212_idx'),
        ),
        migrations.AddConstraint(
            model_name='profilagent',
            constraint=models.CheckConstraint(check=models.Q(('score_performance_global__gte', 0.0), ('score_performance_global__lte', 100.0)), name='etat_civil_profilagent_valid_score'),
        ),
        migrations.AddConstraint(
            model_name='profilagent',
            constraint=models.CheckConstraint(check=models.Q(('capacite_maximale__gte', 1), ('capacite_maximale__lte', 50)), name='etat_civil_profilagent_valid_capacity'),
        ),
        migrations.AddIndex(
            model_name='journalattribution',
            index=models.Index(fields=['dossier', 'action'], name='etat_civil__dossier_eab844_idx'),
        ),
        migrations.AddIndex(
            model_name='attributiondossier',
            index=models.Index(fields=['statut', 'niveau_priorite'], name='etat_civil__statut_a32aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='attributiondossier',
            index=models.Index(fields=['agent', 'statut'], name='etat_civil__agent_i_2014f8_idx'),
        ),
        migrations.AddIndex(
            model_name='attributiondossier',
            index=models.Index(fields=['date_limite_sla'], name='etat_civil__date_li_71cb37_idx'),
        ),
        migrations.AddConstraint(
            model_name='attributiondossier',
            constraint=models.UniqueConstraint(condition=models.Q(('statut__in', ['attribue', 'en_cours'])), fields=('dossier',), name='etat_civil_unique_active_attribution_per_dossier'),
        ),
    ]
