# Generated by Django 4.2.30 on 2026-06-11 18:48

import apps.shared.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communes', '0001_initial'),
        ('etat_civil', '0010_add_attribution_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributiondossier',
            options={'verbose_name': 'Attribution de Dossier', 'verbose_name_plural': 'Attributions de Dossiers'},
        ),
        migrations.AlterModelOptions(
            name='journalattribution',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Journal Attribution', 'verbose_name_plural': 'Journaux Attributions'},
        ),
        migrations.AlterModelOptions(
            name='profilagent',
            options={'verbose_name': 'Profil Agent', 'verbose_name_plural': 'Profils Agents'},
        ),
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('nationalite', models.CharField(default='Sénégalaise', max_length=50, verbose_name='Nationalité')),
                ('telephone', models.CharField(max_length=20, validators=[apps.shared.validators.validate_phone_senegal], verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('quartier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quartier')),
                ('numero_cni', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[apps.shared.validators.validate_cni], verbose_name='Numéro CNI')),
                ('numero_passeport', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de passeport')),
                ('date_expiration_cni', models.DateField(blank=True, null=True, verbose_name="Date d'expiration CNI")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citoyens_guichet', to='communes.commune', verbose_name='Commune')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citoyens_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Citoyen',
                'verbose_name_plural': 'Citoyens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['numero_cni'], name='etat_civil__numero__a32778_idx'), models.Index(fields=['telephone'], name='etat_civil__telepho_264d32_idx'), models.Index(fields=['nom', 'prenom'], name='etat_civil__nom_0c65ed_idx')],
            },
        ),
    ]
