# Generated by Django 4.2.7 on 2026-06-05 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('token', models.CharField(max_length=500, unique=True, verbose_name='Token FCM')),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='web', max_length=15, verbose_name="Type d'appareil")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Token de notification',
                'verbose_name_plural': 'Tokens de notification',
                'indexes': [models.Index(fields=['user'], name='notificatio_user_id_ab2404_idx'), models.Index(fields=['token'], name='notificatio_token_4dafc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('body', models.TextField(verbose_name='Contenu')),
                ('type', models.CharField(choices=[('dossier_submitted', 'Dossier reçu'), ('dossier_approved', 'Dossier validé'), ('dossier_rejected', 'Dossier rejeté'), ('document_available', 'Document disponible'), ('new_dossier', 'Nouveau dossier'), ('urgent_dossier', 'Dossier urgent'), ('action_required', 'Action requise')], db_index=True, max_length=30, verbose_name='Type de notification')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Lu')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Données additionnelles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['type'], name='notificatio_type_ea918f_idx'), models.Index(fields=['-created_at'], name='notificatio_created_ae6ed6_idx')],
            },
        ),
    ]
