# Generated by Django 5.1 on 2026-06-05 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communes', '0001_initial'),
        ('dossiers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('starts_at', models.DateTimeField(verbose_name='Date de début')),
                ('ends_at', models.DateTimeField(verbose_name='Date de fin')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='communes.commune', verbose_name='Commune')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Sondage',
                'verbose_name_plural': 'Sondages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, verbose_name="Texte de l'option")),
                ('votes_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de votes')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='services.survey', verbose_name='Sondage')),
            ],
            options={
                'verbose_name': 'Option de sondage',
                'verbose_name_plural': 'Options de sondage',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('category', models.CharField(choices=[('road', 'Voirie'), ('lighting', 'Éclairage public'), ('waste', 'Déchets / Salubrité'), ('water', 'Eau / Assainissement'), ('security', 'Sécurité'), ('other', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('received', 'Reçu'), ('in_progress', 'En traitement'), ('resolved', 'Résolu'), ('closed', 'Fermé')], default='received', max_length=20, verbose_name='Statut')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/photos/', verbose_name='Photo')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Notes administration')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Citoyen')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='communes.commune', verbose_name='Commune')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='services_re_categor_28bba6_idx'), models.Index(fields=['status'], name='services_re_status_6fa29b_idx'), models.Index(fields=['commune'], name='services_re_commune_25a67f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SurveyVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_votes', to=settings.AUTH_USER_MODEL, verbose_name='Citoyen')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_records', to='services.surveyoption', verbose_name='Option')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='services.survey', verbose_name='Sondage')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'unique_together': {('survey', 'citizen')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence transaction')),
                ('provider', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('free_money', 'Free Money')], max_length=20, verbose_name='Opérateur')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (FCFA)')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('external_transaction_id', models.CharField(blank=True, default='', max_length=255, verbose_name='ID transaction opérateur')),
                ('receipt_url', models.URLField(blank=True, default='', verbose_name='URL reçu PDF')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Citoyen')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='dossiers.dossier', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference'], name='services_tr_referen_f306f9_idx'), models.Index(fields=['citizen'], name='services_tr_citizen_d78ef6_idx'), models.Index(fields=['status'], name='services_tr_status_b8e220_idx'), models.Index(fields=['provider'], name='services_tr_provide_4884c4_idx')],
            },
        ),
    ]
