# Generated by Django 4.2.30 on 2026-06-08 03:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizenprofile',
            options={'verbose_name': 'Profil citoyen'},
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(help_text='Le numéro de téléphone ou email à vérifier', max_length=100, verbose_name='Identifiant (Email ou Téléphone)')),
                ('code', models.CharField(max_length=6, verbose_name='Code OTP')),
                ('is_used', models.BooleanField(default=False, verbose_name='Est utilisé')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Code OTP',
                'verbose_name_plural': 'Codes OTP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['identifier', 'code'], name='users_otpco_identif_4528d2_idx'), models.Index(fields=['is_used'], name='users_otpco_is_used_fa06ee_idx')],
            },
        ),
    ]
