# Generated by Django 4.2.30 on 2026-06-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_loginhistory'),
    ]

    operations = [
    ]
