# Generated by Django 4.2.30 on 2026-06-09 11:53

import apps.shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenprofile',
            name='cni_document',
            field=models.FileField(blank=True, null=True, upload_to='profiles/cni/', verbose_name='Document CNI (Recto/Verso)'),
        ),
        migrations.AlterField(
            model_name='citizenprofile',
            name='cni_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[apps.shared.validators.validate_cni], verbose_name='Num├®ro CNI'),
        ),
        migrations.AlterField(
            model_name='citizenprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de cr├®ation'),
        ),
        migrations.AlterField(
            model_name='citizenprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'F├®minin')], default='', max_length=1, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de cr├®ation'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='identifier',
            field=models.CharField(help_text='Le num├®ro de t├®l├®phone ou email ├á v├®rifier', max_length=100, verbose_name='Identifiant (Email ou T├®l├®phone)'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Est utilis├®'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de cr├®ation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Pr├®nom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='V├®rifi├®'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[apps.shared.validators.validate_phone_senegal], verbose_name='T├®l├®phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citoyen'), ('reception_agent', 'Agent de r├®ception'), ('verification_agent', 'Agent de v├®rification'), ('civil_admin', "Administrateur d'├®tat civil"), ('super_admin', 'Super administrateur')], db_index=True, default='citizen', max_length=25, verbose_name='R├┤le'),
        ),
    ]
