# Generated by Django 4.2.30 on 2026-06-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenprofile',
            name='cni_document',
            field=models.FileField(blank=True, null=True, upload_to='profiles/cni/', verbose_name='Document CNI (Recto/Verso)'),
        ),
    ]
