# Generated by Django 4.2.30 on 2026-06-10 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_citizenprofile_cni_document'),
        ('users', '0004_citizenprofile_cni_document_and_more'),
    ]

    operations = [
    ]
