# Generated by Django 5.1.15 on 2026-06-05 04:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('region', models.CharField(db_index=True, max_length=100, verbose_name='Région')),
                ('department', models.CharField(max_length=100, verbose_name='Département')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code administratif')),
                ('address', models.TextField(blank=True, default='', verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='communes_co_name_9b0e58_idx'), models.Index(fields=['region'], name='communes_co_region_305a1e_idx'), models.Index(fields=['code'], name='communes_co_code_1f2d96_idx')],
            },
        ),
    ]
