# Generated by Django 4.2.7 on 2026-06-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('STATUS_CHANGE', 'Changement de statut'), ('ROLE_CHANGE', 'Changement de rôle'), ('UPLOAD', 'Téléversement'), ('DOWNLOAD', 'Téléchargement'), ('ACCESS_DENIED', 'Accès refusé')], db_index=True, max_length=20, verbose_name='Action'),
        ),
    ]
