# Generated by Django 4.2.30 on 2026-06-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Succès'), ('FAILURE', 'Échec'), ('ERROR', 'Erreur')], db_index=True, default='SUCCESS', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_type',
            field=models.CharField(choices=[('USER', 'Utilisateur'), ('SYSTEM', 'Système'), ('ANONYMOUS', 'Anonyme')], db_index=True, default='USER', max_length=20, verbose_name="Type d'utilisateur"),
        ),
    ]
