# Generated by Django 4.2.30 on 2026-06-10 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NdiogoyeChatLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('message', models.TextField(verbose_name='Message Utilisateur')),
                ('reply', models.TextField(verbose_name='Réponse IA')),
                ('intent', models.CharField(max_length=100, verbose_name='Intention')),
                ('action', models.CharField(blank=True, max_length=100, null=True, verbose_name='Action')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ndiogoye_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Ndiogoye',
                'verbose_name_plural': 'Logs Ndiogoye',
                'ordering': ['-created_at'],
            },
        ),
    ]
