# Generated by Django 5.1.15 on 2026-06-05 04:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Référence')),
                ('type', models.CharField(choices=[('birth_certificate', 'Acte de naissance'), ('marriage_certificate', 'Acte de mariage'), ('death_certificate', 'Acte de décès'), ('residence_certificate', 'Certificat de résidence'), ('other', 'Autre')], db_index=True, max_length=30, verbose_name='Type de dossier')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('in_review', 'En cours de vérification'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('completed', 'Terminé')], db_index=True, default='draft', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Motif de rejet')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DossierComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('content', models.TextField(verbose_name='Contenu')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['created_at'],
            },
        ),
    ]
