# Generated by Django 4.2.30 on 2026-06-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='is_for_third_party',
            field=models.BooleanField(default=False, verbose_name='Pour une tierce personne'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='third_party_cni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNI de la tierce personne'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='third_party_relation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lien de parenté'),
        ),
    ]
