# Generated by Django 4.2.30 on 2026-06-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Métadonnées (Formulaire dynamique)'),
        ),
    ]
