# Generated by Django 4.2.30 on 2026-06-09 01:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('communes', '0001_initial'),
        ('dossiers', '0003_dossier_is_for_third_party_dossier_third_party_cni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Métadonnées du registre'),
        ),
        migrations.CreateModel(
            name='RegistreCivil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('numero_registre', models.CharField(max_length=50, verbose_name='Numéro de registre')),
                ('annee_registre', models.IntegerField(verbose_name='Année de registre')),
                ('type_acte', models.CharField(choices=[('birth_certificate', 'Acte de naissance'), ('marriage_certificate', 'Acte de mariage'), ('death_certificate', 'Acte de décès'), ('residence_certificate', 'Certificat de résidence'), ('other', 'Autre')], max_length=30, verbose_name="Type d'acte")),
                ('nom_complet_personne', models.CharField(max_length=255, verbose_name='Nom complet sur le registre')),
                ('date_naissance_personne', models.DateField(verbose_name='Date de naissance sur le registre')),
                ('conjoint_nom_complet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom complet du conjoint')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registres', to='communes.commune', verbose_name='Commune de déclaration')),
            ],
            options={
                'verbose_name': 'Registre Civil (Simulation)',
                'verbose_name_plural': 'Registres Civils (Simulation)',
                'ordering': ['-annee_registre', 'numero_registre'],
                'unique_together': {('numero_registre', 'annee_registre', 'commune', 'type_acte')},
            },
        ),
    ]
