# Generated by Django 4.2.30 on 2026-06-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0004_dossier_metadata_registrecivil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='type',
            field=models.CharField(choices=[('birth_certificate', 'Extrait de naissance'), ('marriage_certificate', 'Extrait de mariage'), ('death_certificate', 'Certificat de décès'), ('residence_certificate', 'Certificat de résidence'), ('other', 'Autre')], db_index=True, max_length=30, verbose_name='Type de dossier'),
        ),
        migrations.AlterField(
            model_name='registrecivil',
            name='type_acte',
            field=models.CharField(choices=[('birth_certificate', 'Extrait de naissance'), ('marriage_certificate', 'Extrait de mariage'), ('death_certificate', 'Certificat de décès'), ('residence_certificate', 'Certificat de résidence'), ('other', 'Autre')], max_length=30, verbose_name="Type d'acte"),
        ),
    ]
