# Generated by Django 4.2.30 on 2026-06-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0005_alter_dossier_type_alter_registrecivil_type_acte'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrecivil',
            name='jugement_suppletif',
            field=models.BooleanField(default=False, verbose_name='Jugement supplétif'),
        ),
        migrations.AddField(
            model_name='registrecivil',
            name='lieu_naissance',
            field=models.CharField(default='Inconnu', max_length=150, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='registrecivil',
            name='numero_jugement',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de jugement'),
        ),
        migrations.AddField(
            model_name='registrecivil',
            name='prenom_nom_mere',
            field=models.CharField(default='Inconnue', max_length=100, verbose_name='Prénom et Nom de la mère'),
        ),
        migrations.AddField(
            model_name='registrecivil',
            name='prenom_pere',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name='Prénom du père'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('in_review', 'En vérification'), ('generated', 'Généré'), ('validated', 'Validé'), ('delivered', 'Délivré'), ('rejected', 'Rejeté')], db_index=True, default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='registrecivil',
            name='date_naissance_personne',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='registrecivil',
            name='nom_complet_personne',
            field=models.CharField(max_length=255, verbose_name='Nom et Prénoms (Extrait)'),
        ),
    ]
