# Generated by Django 4.2.30 on 2026-06-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0006_registrecivil_jugement_suppletif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrecivil',
            name='nom_complet_personne',
        ),
        migrations.RemoveField(
            model_name='registrecivil',
            name='prenom_nom_mere',
        ),
        migrations.AddField(
            model_name='registrecivil',
            name='heure_naissance',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de naissance'),
        ),
        migrations.AddField(
            model_name='registrecivil',
            name='nom_enfant',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name="Nom de l'enfant"),
        ),
        migrations.AddField(
            model_name='registrecivil',
            name='nom_mere',
            field=models.CharField(default='Inconnue', max_length=100, verbose_name='Nom de la mère'),
        ),
        migrations.AddField(
            model_name='registrecivil',
            name='prenom_mere',
            field=models.CharField(default='Inconnue', max_length=100, verbose_name='Prénoms de la mère'),
        ),
        migrations.AddField(
            model_name='registrecivil',
            name='prenoms_enfant',
            field=models.CharField(default='Inconnu', max_length=150, verbose_name="Prénoms de l'enfant"),
        ),
        migrations.AddField(
            model_name='registrecivil',
            name='sexe',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], default='Masculin', max_length=20, verbose_name='Sexe'),
        ),
    ]
