# Generated by Django 4.2.30 on 2026-06-11 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etat_civil', '0011_alter_attributiondossier_options_and_more'),
        ('dossiers', '0007_remove_registrecivil_nom_complet_personne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='citoyen_guichet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='etat_civil.citoyen', verbose_name='Citoyen (Guichet)'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='citizen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to=settings.AUTH_USER_MODEL, verbose_name='Citoyen'),
        ),
    ]
