# Generated by Django 4.2.30 on 2026-06-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0003_dossier_metadata'),
        ('dossiers', '0008_dossier_citoyen_guichet_alter_dossier_citizen'),
    ]

    operations = [
    ]
