# Generated by Django 4.2.30 on 2026-06-13 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dossiers', '0009_merge_20260612_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='is_for_third_party',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='third_party_cni',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='third_party_relation',
        ),
        migrations.AlterField(
            model_name='dossier',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to=settings.AUTH_USER_MODEL, verbose_name='Citoyen'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('in_review', 'En cours de vérification'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('completed', 'Terminé')], db_index=True, default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='type',
            field=models.CharField(choices=[('birth_certificate', 'Acte de naissance'), ('marriage_certificate', 'Acte de mariage'), ('death_certificate', 'Acte de décès'), ('residence_certificate', 'Certificat de résidence'), ('other', 'Autre')], db_index=True, max_length=30, verbose_name='Type de dossier'),
        ),
        migrations.AlterField(
            model_name='registrecivil',
            name='date_naissance_personne',
            field=models.DateField(null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='registrecivil',
            name='type_acte',
            field=models.CharField(choices=[('birth_certificate', 'Acte de naissance'), ('marriage_certificate', 'Acte de mariage'), ('death_certificate', 'Acte de décès'), ('residence_certificate', 'Certificat de résidence'), ('other', 'Autre')], max_length=30, verbose_name="Type d'acte"),
        ),
    ]
