# Generated by Django 4.2.30 on 2026-06-09 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('otp_hash', models.CharField(max_length=64, verbose_name='Hash du code OTP')),
                ('salt', models.CharField(max_length=32, verbose_name='Sel')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('is_used', models.BooleanField(default=False, verbose_name='Est utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'db_table': 'otp_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
