# Generated by Django 5.1.15 on 2026-06-05 04:56

import apps.documents.models
import apps.shared.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path, validators=[apps.shared.validators.validate_document_file], verbose_name='Fichier')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nom original')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('scan', 'Scan')], max_length=10, verbose_name='Type de fichier')),
                ('file_size', models.IntegerField(verbose_name='Taille (bytes)')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('ocr_status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=15, verbose_name='Statut OCR')),
                ('ocr_text', models.TextField(blank=True, default='', verbose_name='Texte OCR')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
