# Generated by Django 5.1.15 on 2026-06-05 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Téléversé par'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['dossier'], name='documents_d_dossier_f64792_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by'], name='documents_d_uploade_6455fb_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['ocr_status'], name='documents_d_ocr_sta_9ac6e3_idx'),
        ),
    ]
