# Generated by Django 4.2.30 on 2026-06-09 08:57

import apps.documents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0005_alter_dossier_type_alter_registrecivil_type_acte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimbreFiscal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=30, unique=True, verbose_name='Référence du timbre')),
                ('montant', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Montant (FCFA)')),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisé')),
            ],
            options={
                'verbose_name': 'Timbre Fiscal',
                'verbose_name_plural': 'Timbres Fiscaux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedCertificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(upload_to=apps.documents.models.certificate_upload_path, verbose_name='Fichier PDF')),
                ('data_payload', models.TextField(help_text='ref|commune|nom|date_naissance|officier_id|pdf_sha256', verbose_name='Payload signé (données brutes)')),
                ('pdf_sha256', models.CharField(max_length=64, verbose_name='Hash SHA-256 du PDF')),
                ('hmac_signature', models.CharField(max_length=64, verbose_name='Signature HMAC-SHA256')),
                ('cachet_communal_svg', models.CharField(blank=True, default='', max_length=255, verbose_name='Chemin SVG cachet communal')),
                ('signature_officier_svg', models.CharField(blank=True, default='', max_length=255, verbose_name='Chemin SVG signature officier')),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='dossiers.dossier', verbose_name='Dossier')),
                ('officier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Officier signataire')),
                ('timbre', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate', to='documents.timbrefiscal', verbose_name='Timbre fiscal')),
            ],
            options={
                'verbose_name': 'Certificat Généré',
                'verbose_name_plural': 'Certificats Générés',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dossier'], name='documents_g_dossier_4544e0_idx'), models.Index(fields=['hmac_signature'], name='documents_g_hmac_si_9adc04_idx')],
            },
        ),
    ]
