# Generated by Django 4.2.30 on 2026-06-09 14:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('currency', models.CharField(default='XOF', max_length=10, verbose_name='Devise')),
                ('payment_type', models.CharField(choices=[('card', 'Carte bancaire (CB/Visa/Mastercard)'), ('wave', 'Mobile Money Wave'), ('orange_money', 'Mobile Money Orange Money'), ('free_money', 'Mobile Money Free Money'), ('transfer', 'Virement bancaire'), ('agency', 'Paiement en agence'), ('cash', 'Espèces (caisse)')], max_length=30, verbose_name='Type de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Validé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('payer_name', models.CharField(max_length=150, verbose_name='Nom du payeur')),
                ('payer_id', models.CharField(max_length=100, verbose_name='Identifiant du payeur')),
                ('service_label', models.CharField(max_length=200, verbose_name='Libellé du service')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transferred_at', models.DateTimeField(verbose_name='Date de transfert')),
                ('transfer_reference', models.CharField(max_length=100, verbose_name='Référence de transfert')),
                ('validated_by', models.CharField(default='system', max_length=50, verbose_name='Validé par')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_transfers', to='payments.paymenttransaction', verbose_name='Transaction')),
            ],
            options={
                'db_table': 'treasury_transfers',
                'ordering': ['-transferred_at'],
            },
        ),
    ]
